name: Database Migration Check

on:
  pull_request:
    paths:
      - 'prisma/**'

env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  SHADOW_DATABASE_URL: postgresql://postgres:postgres@localhost:5432/shadow

jobs:
  database-migration-check:
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: shadow
        ports:
          - '5432:5432'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - run: npm ci
      - run: npx prisma generate
      - run: npx prisma validate
      - run: npx prisma migrate diff --from-migrations ./prisma/migrations --to-schema ./prisma/schema.prisma --exit-code
